"""empty message

Revision ID: 31be8c31c52c
Revises: dbdf427f56f1
Create Date: 2024-10-05 15:42:57.820007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31be8c31c52c'
down_revision: Union[str, None] = 'dbdf427f56f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'product_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
