"""empty message

Revision ID: 98349d1e66b3
Revises: c89a019488e0
Create Date: 2024-10-13 12:19:00.262096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98349d1e66b3'
down_revision: Union[str, None] = 'c89a019488e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('order_id', sa.BigInteger(), nullable=True))
    op.add_column('order_items', sa.Column('product_id', sa.BigInteger(), nullable=True))
    op.drop_index('ix_order_items_ix_order_items_order_id', table_name='order_items')
    op.drop_index('ix_order_items_ix_order_items_product_id', table_name='order_items')
    op.drop_constraint('ix_order_id_product_id', 'order_items', type_='unique')
    op.create_unique_constraint('ix_order_id_product_id', 'order_items', ['order_id', 'product_id'])
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.drop_constraint('order_items_ix_order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_ix_order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order_items', 'ix_order_items_order_id')
    op.drop_column('order_items', 'ix_order_items_product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('ix_order_items_product_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('ix_order_items_order_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_ix_order_items_product_id_fkey', 'order_items', 'products', ['ix_order_items_product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('order_items_ix_order_items_order_id_fkey', 'order_items', 'orders', ['ix_order_items_order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_constraint('ix_order_id_product_id', 'order_items', type_='unique')
    op.create_unique_constraint('ix_order_id_product_id', 'order_items', ['ix_order_items_order_id', 'ix_order_items_product_id'])
    op.create_index('ix_order_items_ix_order_items_product_id', 'order_items', ['ix_order_items_product_id'], unique=False)
    op.create_index('ix_order_items_ix_order_items_order_id', 'order_items', ['ix_order_items_order_id'], unique=False)
    op.drop_column('order_items', 'product_id')
    op.drop_column('order_items', 'order_id')
    # ### end Alembic commands ###
