"""empty message

Revision ID: bd4f9c53b852
Revises: ce4c832c4f25
Create Date: 2024-10-07 02:19:21.215379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4f9c53b852'
down_revision: Union[str, None] = 'ce4c832c4f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_count', sa.Integer(), nullable=False))
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'product_count')
    # ### end Alembic commands ###
