"""empty message

Revision ID: c89a019488e0
Revises: 339a9117bdf5
Create Date: 2024-10-13 03:20:14.395009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89a019488e0'
down_revision: Union[str, None] = '339a9117bdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ix_order_id_product_id', 'order_items', ['ix_order_items_order_id', 'ix_order_items_product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_order_id_product_id', 'order_items', type_='unique')
    # ### end Alembic commands ###
