"""empty message

Revision ID: dbdf427f56f1
Revises: aaaa8ec55027
Create Date: 2024-10-05 15:41:20.807242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdf427f56f1'
down_revision: Union[str, None] = 'aaaa8ec55027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
